#!/bin/bash

#auto update the build time
grep -v "^Packaged:" copyCat/DESCRIPTION >zz
mv -f zz copyCat/DESCRIPTION
thedate=`date +"%F %r"`;
echo "Packaged: $thedate; cmiller" >>copyCat/DESCRIPTION

version=$(grep "Version" copyCat/DESCRIPTION | awk '{print $2}')

R CMD build copyCat && R CMD INSTALL copyCat_$version.tar.gz
